spring:
  application:
    name: store
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 # 15m
    refreshTokenExpiration: 604800 # 7d
  profiles:
    active: dev
stripe:
  secret: ${STRIPE_SECRET}
  webhookSecret: ${STRIPE_WEBHOOK_SECRET}
